### ISSUE TITLE
Implement update function

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-cache#8]
I have some cool code that uses getActiveVersion to make sure the cache is always uptodate.

If the node has changed I need to do two things:
1. remove(key)
2. get(key, fn)

I would like a update(key, fn) function that would overwrite the cache.
Perhaps it could be optimized because it does not need to check wether key already exists.

**Comment by GlennRicaud** [comment]
Not recommended. Better to just invalidate and get.

Also the current implementation of this issue can cause problems (race condition).
To be reverted and untagged
